#!/bin/bash

#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
docker buildx create --name mybuilder --driver docker-container --use
docker buildx use mybuilder
docker buildx inspect --bootstrap
docker buildx ls
